<?php
/**
 * Implements hook_help.
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function cms2cms_help($path, $arg)
{
    switch ($path) {
        case "admin/help#cms2cms":
            return '<p>' . t("Automated cms migration") . '</p>';
            break;
    }
}


/**
 * Implements hook_contents().
 */
function cms2cms_contents()
{
    return "cms2cms_contents";
}

/**
 * Implements hook_menu().
 */
function cms2cms_menu()
{
    $items = array();

    $items['admin/config/content/cms2cms'] = array(
        'title' => 'cms2cms automated cms migration',
        'description' => 'Configuration for Current posts module',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cms2cms'),
        'access arguments' => array('access administration pages'),
        'type' => MENU_CONTEXT_PAGE,
    );

    return $items;
}

function cms2cms_form($form, &$form_state)
{
    $form['cms2cms_max'] = array(
        '#type' => 'textfield',
        '#title' => t('Maximum number of posts'),
        '#default_value' => 3,
        '#size' => 2,
        '#maxlength' => 2,
        '#description' => t('The maximum number of links to display in the block.'),
        '#required' => TRUE,
    );
    return system_settings_form($form);
}