<?php
/**
 * Implements hook_help.
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function cms2cms_help($path, $arg) {
    switch ($path) {
        case "admin/help#cms2cms":
            return '<p>' . t("Automated cms migration") . '</p>';
            break;
    }
}

/**
 * Implements hook_block_info().
 */
function cms2cms_block_info() {
    $blocks['cms2cms'] = array(
        // The name that will appear in the block list.
        'info' => t('CMS2CMS automated cms migration'),
        // Default setting.
        'cache' => DRUPAL_CACHE_PER_ROLE,
    );
    return $blocks;
}

/**
 * Implements hook_contents().
 */
function cms2cms_contents() {
    return "cms2cms_contents";
}

/**
 * Implements hook_menu().
 */
function current_posts_menu() {
    $items = array();

    $items['admin/config/content/cms2cms'] = array(
        'title' => 'cms2cms automated cms migration',
        'description' => 'Configuration for Current posts module',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cms2cms'),
        'access arguments' => array('access administration pages'),
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}